version: "3"
services:
  ibench:   
    image: 0.0.0.0:5000/ibench
    deploy:
      replicas: 1
      resources:
        limits:
            cpus: "1"
            memory: 512M
      placement:
        constraints: [node.hostname==worker9]
    ports: 
      - "9001:9000"
    environment:
      - CPU_COUNT=0
      - SERVER_PORT=9000
      - NODE_SERVER_PORT=9001
      - SERVER_IP=0.0.0.0
      - PRIME=10971096049

networks:
  webnet:
    
