version: "3"
services:
  ibench:
    container_name: ibench
    image: 192.168.1.178:5001/ibench
    deploy:
      replicas: 1
      resources:
        limits:
            cpus: "2.5"
            memory: 2048M
      placement:
        constraints: [node.hostname==worker6]
    ports:
      - "9001:9000"
    environment:
      - CPU_COUNT=0
      - SERVER_PORT=9000
      - NODE_SERVER_PORT=9001
      - SERVER_IP=0.0.0.0
      - TEXT_IN_BYTES=31457.28
    networks:
      - webnet
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - webnet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == manager
networks:
  webnet:
